name: DailyExtract

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行
  workflow_dispatch: # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Run extract script
        run: |
          chmod +x ./extract.sh
          ./extract.sh

      - name: Move output.txt to Clash_Rule folder
        run: |
          mkdir -p Clash_Rule  # 确保 Clash_Rule 文件夹存在
          mv output.txt Clash_Rule/

      - name: Commit and push changes
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ secrets.USERNAME }}"
          git add Clash_Rule/output.txt
          git commit -m "Update output.txt in Clash_Rule folder" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
