name: DailyExtract

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行
  workflow_dispatch: # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Run extract script
        run: |
          #!/bin/bash
          # 下载文件并提取第一个匹配，添加 /32,no-resolve
          response=$(curl -s https://gitee.com/sunhaoyuan55/tool/raw/ceshi/ipv4.m3u)
          echo "$response"  # 输出内容

          # 使用 grep 匹配 IP 地址并将结果存储在变量中
          matched_ips=$(echo "$response" | grep -Eo '((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)')
          
          # 输出匹配的结果
          echo "$matched_ips"

          # 将匹配结果进一步处理并保存到文件
          echo "$matched_ips" | sort -u | sed 's/$/\/32,no-resolve/' > iptv_address.txt

      - name: Move iptv_address.txt to Clash_Rule folder
        run: |
          mkdir -p Clash_Rule  # 确保 Clash_Rule 文件夹存在
          mv iptv_address.txt Clash_Rule/

      - name: Commit and push changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "eedaniel12"
          git add Clash_Rule/iptv_address.txt
          git commit -m "Update iptv_address.txt in Clash_Rule folder" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
