name: DailyExtract

on:
  schedule:
    - cron: '0 0,12 * * *' # 每天 UTC 时间午夜运行
  workflow_dispatch: # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests

      # Download ipv4.m3u file
      - name: Download ipv4.m3u
        run: |
          curl -L --fail -o ipv4.m3u https://gitee.com/sunhaoyuan55/tool/raw/ceshi/ipv4.m3u

      # Run Python script to process the file
      - name: Run extract script
        run: |
          python -c "
          import re
          import requests

          with open('ipv4.m3u', 'r') as file:
            content = file.read()

          domain_pattern = r'(?<=://)(?:([a-zA-Z0-9.-]+))'
          domains = re.findall(domain_pattern, content)

          ipv4_pattern = r'(?<=://)(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
          ipv4s = re.findall(ipv4_pattern, content)

          ipv6_pattern = r'(?<=://\[)([0-9a-fA-F:]+)(?=\])'
          ipv6s = re.findall(ipv6_pattern, content)

          with open('iptv_address.txt', 'a') as output_file:
            output_file.write('payload:\n')
            for domain in set(domains):
              if domain not in set(ipv4s):
                output_file.write(f'  - Domain,{domain}\n')
            for ipv4 in set(ipv4s):
              output_file.write(f'  - IP-CIDR,{ipv4}/32,no-resolve\n')
            for ipv6 in set(ipv6s):
              output_file.write(f'  - IP-CIDR6,{ipv6}/128,no-resolve\n')
          "


      - name: Move iptv_address.txt to Clash_Rule folder
        run: |
          mkdir -p Clash_Rule  # 确保 Clash_Rule 文件夹存在
          mv iptv_address.txt Clash_Rule/

      - name: Commit and push changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "eedaniel12"
          git add Clash_Rule/iptv_address.txt
          git commit -m "Update iptv_address.txt in Clash_Rule folder" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
